# Notebook 1: Dataset Understanding

#### Overview
- **Dataset Name:** Customer Retention & Churn Dataset
- **File Name:** `Customer_Data.csv`

In [19]:
import pandas as pd

# Load dataset
df = pd.read_csv("Customer_Data.csv")
df.head()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.12,394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.53,796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes

### 1. Dataset
A **Dataset** is a structured collection of data points organized into rows (records) and columns (features).

In [21]:
df.head(10)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.12,394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.53,796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes
5,CUST00006,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
6,CUST00007,69.0,Male,9,21.12,394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
7,CUST00008,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
8,CUST00009,32.0,Male,8,35.53,796.58,Month-to-month,No,Credit card,No,2,No,No,No
9,CUST00010,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes

### 1. Dataset
A **Dataset** is a structured collection of data points organized into rows (records) and columns (features).

In [22]:

df.head(10)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.12,394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.53,796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes
5,CUST00006,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
6,CUST00007,69.0,Male,9,21.12,394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
7,CUST00008,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
8,CUST00009,32.0,Male,8,35.53,796.58,Month-to-month,No,Credit card,No,2,No,No,No
9,CUST00010,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes

### 2. Feature
A **Feature** is an individual measurable property or column in a dataset.

In [23]:
# List all features
print("Dataset Features:")
print(list(df.columns))

Dataset Features:
['CustomerID', 'Age', 'Gender', 'TenureYears', 'MonthlyCharges', 'TotalCharges', 'ContractType', 'InternetService', 'PaymentMethod', 'SeniorCitizen', 'SupportCalls', 'StreamingService', 'PaperlessBilling', 'Churn']

### 3. Target Variable
The **Target** is the specific column we want our predictive model to forecast. Here, `Churn` is our target.

In [24]:
# Check target distribution
print(df["Churn"].value_counts())

Churn
No     3600
Yes    2400
Name: count, dtype: int64

### 4. Independent & Dependent Variables
- **Independent Variables ($X$):** The predictor columns used as inputs.
- **Dependent Variable ($y$):** The outcome being predicted (`Churn`).

In [25]:
# Separate predictors (X) and target (y)
X = df.drop(columns=["Churn"])
y = df["Churn"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (6000, 13)
y shape: (6000,)

### 5. Numerical vs Categorical Features
- **Numerical:** Quantitative counts or measurements (`Age`, `MonthlyCharges`, `TenureYears`).
- **Categorical:** Qualitative categories or text labels (`Gender`, `ContractType`, `PaymentMethod`).

In [26]:
# Identify numerical vs categorical
num_cols = df.select_dtypes(include=["number"]).columns
cat_cols = df.select_dtypes(include=["object"]).columns

print("Numerical Columns:", list(num_cols))
print("Categorical Columns:", list(cat_cols))

Numerical Columns: ['Age', 'TenureYears', 'MonthlyCharges', 'TotalCharges', 'SupportCalls']
Categorical Columns: ['CustomerID', 'Gender', 'ContractType', 'InternetService', 'PaymentMethod', 'SeniorCitizen', 'StreamingService', 'PaperlessBilling', 'Churn']

C:\Users\abarn\AppData\Local\Temp\ipykernel_20128\1824459192.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=["object"]).columns

### 6. Metadata & Dimensions
Metadata provides structural information including data types, non-null counts, and shape.

In [27]:
# View dataset structure and dimensions
df.info()
print("\nShape (Rows, Columns):", df.shape)

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        6000 non-null   str
 1   Age               6000 non-null   float64
 2   Gender            6000 non-null   str
 3   TenureYears       6000 non-null   int64
 4   MonthlyCharges    6000 non-null   float64
 5   TotalCharges      6000 non-null   float64
 6   ContractType      6000 non-null   str
 7   InternetService   6000 non-null   str
 8   PaymentMethod     6000 non-null   str
 9   SeniorCitizen     6000 non-null   str
 10  SupportCalls      6000 non-null   int64
 11  StreamingService  6000 non-null   str
 12  PaperlessBilling  6000 non-null   str
 13  Churn             6000 non-null   str
dtypes: float64(3), int64(2), str(9)
memory usage: 948.2 KB

Shape (Rows, Columns): (6000, 14)