# Notebook 2: Data Inspection

#### Overview
Perform deep inspection on `Customer_Data.csv` including structural dimensions, data types, statistical previews, and column classification.

In [11]:
import pandas as pd

# Load the dataset
df = pd.read_csv("Customer_Data.csv")
df.head()

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
0,CUST00001,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
1,CUST00002,69.0,Male,9,21.12,394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2,CUST00003,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3,CUST00004,32.0,Male,8,35.53,796.58,Month-to-month,No,Credit card,No,2,No,No,No
4,CUST00005,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes

### 1. Number of Rows & 2. Number of Columns
Retrieving individual axis dimensions of the dataset.

In [12]:
print("Number of Rows:", len(df))
print("Number of Columns:", len(df.columns))

Number of Rows: 6000
Number of Columns: 14

### 3. Data Types & dtypes
Inspecting low-level memory representations and Python data types for every feature.

In [13]:
print("--- Column Data Types ---")
print(df.dtypes)

--- Column Data Types ---
CustomerID              str
Age                 float64
Gender                  str
TenureYears           int64
MonthlyCharges      float64
TotalCharges        float64
ContractType            str
InternetService         str
PaymentMethod           str
SeniorCitizen           str
SupportCalls          int64
StreamingService        str
PaperlessBilling        str
Churn                   str
dtype: object

### 4. Column Names & 5. Index
Checking structural feature headers and row indexing boundaries.

In [14]:
print("Column Names:", list(df.columns))
print("\nDataset Index:", df.index)

Column Names: ['CustomerID', 'Age', 'Gender', 'TenureYears', 'MonthlyCharges', 'TotalCharges', 'ContractType', 'InternetService', 'PaymentMethod', 'SeniorCitizen', 'SupportCalls', 'StreamingService', 'PaperlessBilling', 'Churn']

Dataset Index: RangeIndex(start=0, stop=6000, step=1)

### 6. head(), 7. tail(), and 8. sample()
Inspecting top records, bottom records, and random subsets to catch data anomalies.

In [15]:
# View first 5 rows
df.head()

# View last 5 rows
df.tail()

# View 5 randomly sampled rows
df.sample(5, random_state=42)

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,InternetService,PaymentMethod,SeniorCitizen,SupportCalls,StreamingService,PaperlessBilling,Churn
1782,CUST01783,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
3917,CUST03918,46.0,Female,3,61.66,2755.45,Two year,DSL,Bank transfer,No,3,Yes,No,No
221,CUST00222,69.0,Male,9,21.12,394.45,Two year,DSL,Credit card,Yes,1,Yes,No,No
2135,CUST02136,56.0,Female,0,20.41,131.92,One year,DSL,Bank transfer,No,3,No,Yes,Yes
5224,CUST05225,60.0,Male,9,86.45,10188.80,Two year,Fiber optic,Electronic check,Yes,3,No,Yes,Yes